### PR TITLE
Remove remaining occurrences of "@xxx" from non-pdf versions

### LINKED ISSUE #591: The register machine simulator doesn't work, due to occurrences of "@xxx" in the code.
Try any of the examples in [Section 5.2](https://sourceacademy.org/sicpjs/5.2).  You'll get the following when you attempt to run them
```
Line 89: SyntaxError: Unexpected character '@' (89:0)
```

Then if you check the code you will see the string `@xxx` there and a bunch of other places.

### PR DESCRIPTION
**Pull request by samuelfangjw**
Closes #591 

- ~Accounted for possibility that "@xxx" is not followed by newline character.~
- ~Replaced `SHORT_SPACE` and `SHORT_SPACE_ALLOW_BREAK` with newline character in non-pdf versions.~
- Removed dead code from `processSnippetJs`

EDIT:
- Set default transformation of relevant xml tags to empty string
- Set transformation of relevant tags in pdf version to "@xxx" and "@yyy"

### CODE REVIEW

**Comment by TobiasWrigstad** [comment]
Thank you @samuelfangjw! 

However, in hindsight -- would it not be better to bypass the transformation from XML tags to @xxx, etc.? initially, I used a simpler marker directly in the code in the snippets, but then we moved to a proper XML tag.

**Comment by samuelfangjw** [comment]
> Thank you @samuelfangjw!
> 
> However, in hindsight -- would it not be better to bypass the transformation from XML tags to @xxx, etc.? initially, I used a simpler marker directly in the code in the snippets, but then we moved to a proper XML tag.

Agreed! It would be much neater that way. I originally didn't want to make any unnecessary changes that might affect the pdf version (while we are trying to get the book published), hence this ugly stopgap solution.

I took a quick look, I believe bypassing the transformation may not be as simple as it seems, since in the pdf version "@yyy" is transformed into either `separator`(line 253)  or `seperator2`(line 401) depending on context, so we would have to transform the tag into some kind of placeholder value anyways (might be wrong here). 

However, seems like it would be pretty simple to limit the transformation of XML tags to just the pdf version for now. Would this be better?

I'll take a closer look at this and make any necessary changes tomorrow!

File: javascript/processingFunctions/processSnippetJs.js [hunk 1]
```diff
@@ -87,17 +85,12 @@ export const processSnippetJs = (node, writeTo, fileFormat) => {
         jsRunSnippet = jsSnippet;
       }
     }
-    const codeArr = [];
```
Comment (samuelfangjw) [inline javascript/processingFunctions/processSnippetJs.js:90]: Dead code, variable not used

File: javascript/processingFunctions/replaceTagWithSymbol.js [hunk 2]
```diff
@@ -34,8 +34,23 @@ const tagsToReplace = {
   FIXED_SPACE: "{\\tt~}"
 };
 
-export const replaceTagWithSymbol = (node, writeTo) => {
+const tagsToReplacePdf = {
+  SHORT_SPACE: "@xxx", // will be replaced in processSnippet
+  SHORT_SPACE_AND_ALLOW_BREAK: "@yyy" // will be replaced in processSnippet
+};
+
+export const replaceTagWithSymbol = (node, writeTo, type = "default") => {
```
Comment (samuelfangjw) [inline javascript/processingFunctions/replaceTagWithSymbol.js:42]: Add parameter type. `SHORT_SPACE` and `SHORT_SPACE_AND_ALLOW_BREAK` are replaced if `type === "pdf"`

**Comment by samuelfangjw** [comment]
Hi @TobiasWrigstad, I've made some changes:
- Default transformation of `SHORT_SPACE` and `SHORT_SPACE_AND_ALLOW_BREAK` is now empty string.
- For the pdf version, tags are transformed into "@xxx" and "@yyy", which are then handled in `processSnippetPdf`.

I think it would be great if we could get rid of the use of the placeholder values "@xxx" and "@yyy" entirely, but I feel it might be more trouble than it's worth at this point (Not a straightforward swap since "@yyy" is replaced either by `separator` or `seperator2` depending on whether context. I believe we would have to add a check for whether the parent node has `EVAL === "no" || LATEX === "yes"`, which I feel might add more complexity rather than simplify things).

Could you kindly help to review the PR, thanks in advance! I've also attached the pdf version created by `yarn pdf` so we can verify any changes.

[sicpjs.pdf](https://github.com/source-academy/sicp/files/6948778/sicpjs.pdf)

**Comment by TobiasWrigstad** [comment]
Great @samuelfangjw! I will be able to look at this later today.

**Comment by TobiasWrigstad** [comment]
Hi @samuelfangjw ! 

There is something odd happening. Compare for example page 492 (aka 524) in your PDF with the same page (482 aka 514) in the master build. Here is yours:
image
Note how the line spacing before the last line has been messed up. 

Here is the same in the master build for comparison:
image

I haven't looked in the generated LaTeX (yet) but I cannot see the reason for this in the code you've written. Did you touch the LaTeX files at all? (I presume not.)

File: javascript/processingFunctions/replaceTagWithSymbol.js [hunk 3]
```diff
@@ -22,8 +22,8 @@ const tagsToReplace = {
   SHARP: "\\#",
   SECT: "§",
 
-  SHORT_SPACE: "@xxx", // will be replaced in processSnippet depending on rendering target (PDF, HTML, etc.)
-  SHORT_SPACE_AND_ALLOW_BREAK: "@yyy", // will be replaced in processSnippet depending on rendering target (PDF, HTML, etc.)
+  SHORT_SPACE: "",
+  SHORT_SPACE_AND_ALLOW_BREAK: "",
```
Comment (TobiasWrigstad) [inline javascript/processingFunctions/replaceTagWithSymbol.js:26]: Would it make sense to replace these with "\n" right here?

**Comment by TobiasWrigstad** [comment]
@samuelfangjw -- your PDF has 10 pages more than the master branch. See page 6 for example, where the master branch fits 1 more line on the page. Is your code "old"? Your hyphenation seems different.

**Comment by TobiasWrigstad** [comment]
I made some comments above and then deleted them. I made a very stupid mistake and was looking at another file than yours dues to browser renaming it on download...

File: javascript/processingFunctions/replaceTagWithSymbol.js (hunk 3 above)
Comment (TobiasWrigstad) [reply javascript/processingFunctions/replaceTagWithSymbol.js:26]: Ah, wait. That's the effect of replacing the tag by "", presumably.

**Review by TobiasWrigstad — APPROVED** [review]
I've compared the right two pdfs now :) This is great.

File: javascript/processingFunctions/replaceTagWithSymbol.js (hunk 3 above)
Comment (samuelfangjw) [reply javascript/processingFunctions/replaceTagWithSymbol.js:26]: Thanks @TobiasWrigstad for the review! Yes, I would have thought "\n" would have been more appropriate here, but it seems to add an extra line break (replaced by two blank lines instead of one). 

Original: replace by "@xxx":
Screenshot 2021-08-08 at 7 08 01 AM

Replace with "\n":
Screenshot 2021-08-08 at 7 08 45 AM

Replace  with "":
Screenshot 2021-08-08 at 7 09 13 AM
